apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-persistent-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions: 
      -Xms: 1536m
      -Xmx: 1536m
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    listeners:
      # Enable the plain interface
      plain: {}
      # Enable the TLS interface
      tls: {}
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        class: ocs-storagecluster-ceph-rbd
        deleteClaim: false
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 500m
    jvmOptions: 
      -Xms: 1536m
      -Xmx: 1536m
    storage:
      type: persistent-claim
      size: 100Gi
      class: ocs-storagecluster-ceph-rbd
      deleteClaim: false
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 500m
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 500m